# Configure the Reactive Postgres driver (default for new Quarkus apps)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=secret
quarkus.datasource.jdbc.url=jdbc:postgresql://127.0.0.1:5432/fiscalizai_db

# Database generation strategy (updates schema automatically)
quarkus.hibernate-orm.schema-management.strategy=drop-and-create

# Import initial data
quarkus.hibernate-orm.sql-load-script=import.sql
