############### GLOBAL ##################################

quarkus.http.port=${PORT:8080}

#Default locale for the application and supported locales
quarkus.default-locale=pt_BR
quarkus.locales=en,pt-BR,pt

############### DEV ##################################

# Configure the Reactive Postgres driver (default for new Quarkus apps)
%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.username=postgres
%dev.quarkus.datasource.password=secret
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://127.0.0.1:5432/fiscalizai_db

# Database generation strategy (updates schema automatically)
%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create

# Import initial data
%dev.quarkus.hibernate-orm.sql-load-script=import.sql

############### PROD ##################################

# 1. Choose the production profile
%prod.quarkus.datasource.db-kind=postgresql

# 2. Database connection credentials (using Environment Variables)
%prod.quarkus.datasource.username=${DB_USERNAME}
%prod.quarkus.datasource.password=${DB_PASSWORD}

# 3. Database URL (Reactive vs JDBC)
# If using the Reactive SQL Client:
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require

# 4. Database schema management (updates schema automatically in production if desired)
%prod.quarkus.hibernate-orm.schema-management.strategy=drop-and-create

# Import initial data
%prod.quarkus.hibernate-orm.sql-load-script=import.sql